;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                                        ;
;                                      BOOLEAN.INC                                       ;
;                                Contains Boolean values                                 ;
;                                     Tim Menninger                                      ;
;                                                                                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;	

;This file contains general Boolean constants
;Revision History:
;       11/28/14    Tim Menninger   Created 

;General Constants
TRUE			EQU	1				;boolean TRUE
FALSE			EQU 0				;boolean FALSE